### ISSUE TITLE
Sudden death with auto restart doesn't give pp?

### ISSUE THREAD

**Issue by lolololer1337228** [ppy/osu-queue-score-statistics#213] opened 2024-02-01 04:01 UTC
[Score](https://osu.ppy.sh/scores/2265588321), it's the only score I think that doesn't have pp on the leaderboards of this beatmap.

**Comment by frenzibyte** [comment] 2024-02-01 04:15
Duplicate of https://github.com/ppy/osu/issues/26844

**Closed by frenzibyte** 2024-02-01 04:15 UTC
